# Generated by Django 4.0.4 on 2022-04-29 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Customer Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=512)),
                ('number', models.IntegerField(max_length=10)),
                ('cep', models.IntegerField()),
                ('complement', models.CharField(max_length=64)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('water_per_day', models.FloatField(verbose_name='Recommended water volume per day (mm)')),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('start_season', models.DateField()),
                ('end_season', models.DateField()),
                ('harvest', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.farm')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Water_Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tank Name')),
                ('total_capacity', models.FloatField()),
                ('current_capacity', models.FloatField()),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Plantation_Water_Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('programmed_volume_water', models.FloatField()),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.IntegerField(choices=[('1', 'Dono/Fazendeiro'), ('2', 'Gerente de Fazenda'), ('3', 'Parente'), ('4', 'Outros')])),
                ('name', models.CharField(max_length=256, verbose_name='Contact Name')),
                ('cellphone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('main_contact', models.BooleanField()),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Climate_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateTimeField()),
                ('wind_kph', models.FloatField()),
                ('precip_mm', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temp_c', models.FloatField()),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Audit_Water_Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('used_water', models.FloatField()),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcs_app.plantation_water_routine')),
            ],
        ),
    ]
